apiVersion: v1
kind: Pod
metadata:
  name: python-pod
spec:
  containers:
  - name: python
    image: python:3.9
    command: ["/bin/bash", "-c"]
    args:
      - pip install confluent-kafka
        && sleep infinity
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    resources:
      limits:
        memory: "1000Mi"
        cpu: "1000m"
